# Reference documentation: https://docs.gitlab.com/ee/ci/yaml/README.html
---
image: ubuntu

before_script:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends $(cat apt-requirements.txt)

test:
  script:
    - make test

kmod-build-ubuntu-generic:
  script:
    - make qp_kmod_test__ubuntu_generic.ko

docs:
  script:
    - doxygen
  artifacts:
    expose_as: docs
    paths:
      - html

build-docker-cmake-clang:
  image: docker
  before_script: []
  script: docker build . -f Dockerfile.cmake_clang
  tags: [cdleonard,privileged-docker-access]

pages:
  stage: deploy
  before_script: []
  dependencies:
    - docs
  script:
    - mkdir -p public
    - mv html public/doxygen-html/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
