# Reference documentation: https://docs.gitlab.com/ee/ci/yaml/README.html
---
image: ubuntu

test:
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
        check
        pkg-config
        libc-dev
        make
        gcc
  script:
    - make test

docs:
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends doxygen
  script:
    - doxygen
  artifacts:
    expose_as: docs
    paths:
      - html
