#
# Run with docker build . -f Dockerfile.ubuntu
#
FROM ubuntu
COPY apt-requirements.txt ./
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
        dumb-init \
        $(cat apt-requirements.txt) \
&& rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
